name: pages build and deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci

      - name: Build Angular
        run: npx ng build --configuration=production --base-href "/Hire-Me/"

      - name: Locate build dir
        id: out
        run: |
          if [ -d dist/HireMe/browser ]; then
            echo "PATH=dist/HireMe/browser" >> $GITHUB_OUTPUT
          else
            echo "PATH=dist/HireMe" >> $GITHUB_OUTPUT
          fi

      - name: SPA 404
        run: |
          cp "${{ steps.out.outputs.PATH }}/index.html" "${{ steps.out.outputs.PATH }}/404.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.out.outputs.PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: out

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: gh-pages
          enable_jekyll: false
